export const API_URL = "http://localhost:5000/";
// DONOR USER ACTIONS
export const REGISTER_DONOR_USER = "REGISTER_DONOR_USER";
export const REGISTER_DONOR_USER_SUCCESS = "REGISTER_DONOR_USER_SUCCESS";
export const REGISTER_DONOR_USER_FAILED = "REGISTER_DONOR_USER_FAILED";
export const REGISTER_DONOR_USER_CANCEL = "REGISTER_DONOR_USER_CANCEL";
export const LOGIN_DONOR = "LOGIN_DONOR";
export const LOGIN_DONOR_CANCEL = "LOGIN_DONOR_CANCEL";
export const LOGIN_DONOR_SUCCESS = "LOGIN_DONOR_SUCCESS";
export const LOGIN_DONOR_FAILED = "LOGIN_DONOR_FAILED";

// NEEDY USER ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_CANCEL = "LOGIN_USER_CANCEL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const REGISTER_USER_CANCEL = "REGISTER_USER_CANCEL";
// CREATE LISTINGS
export const CREATE_LISTING = "CREATE_LISTING";
export const CREATE_LISTING_SUCCESS = "CREATE_LISTING_SUCCESS";
export const CREATE_LISTING_FAILED = "CREATE_LISTING_FAILED";
export const CREATE_LISTING_CANCEL = "CREATE_LISTING_CANCEL";


export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";