export const API_URL = "http://localhost:5000/";
// DONOR USER ACTIONS
export const REGISTER_DONOR_USER = "REGISTER_DONOR_USER";
export const REGISTER_DONOR_USER_SUCCESS = "REGISTER_DONOR_USER_SUCCESS";
export const REGISTER_DONOR_USER_FAILED = "REGISTER_DONOR_USER_FAILED";
export const REGISTER_DONOR_USER_CANCEL = "REGISTER_DONOR_USER_CANCEL";

// NEEDY USER ACTIONS
export const REGISTER_NEEDY_USER = "REGISTER_NEEDY_USER";
export const REGISTER_NEEDY_USER_SUCCESS = "REGISTER_NEEDY_USER_SUCCESS";
export const REGISTER_NEEDY_USER_FAILED = "REGISTER_NEEDY_USER_FAILED";
export const REGISTER_NEEDY_USER_CANCEL = "REGISTER_NEEDY_USER_CANCEL";
// export const REGISTER_DONOR_USER = "REGISTER_DONOR_USER";
