// settings for front end
export const API_URL = "http://localhost:5000/";
export const allowedTitleChars = 105;
// DONOR USER ACTIONS
export const REGISTER_DONOR_USER = "REGISTER_DONOR_USER";
export const REGISTER_DONOR_USER_SUCCESS = "REGISTER_DONOR_USER_SUCCESS";
export const REGISTER_DONOR_USER_FAILED = "REGISTER_DONOR_USER_FAILED";
export const REGISTER_DONOR_USER_CANCEL = "REGISTER_DONOR_USER_CANCEL";
export const LOGIN_DONOR = "LOGIN_DONOR";
export const LOGIN_DONOR_CANCEL = "LOGIN_DONOR_CANCEL";
export const LOGIN_DONOR_SUCCESS = "LOGIN_DONOR_SUCCESS";
export const LOGIN_DONOR_FAILED = "LOGIN_DONOR_FAILED";

// NEEDY USER ACTIONS
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_CANCEL = "LOGIN_USER_CANCEL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const REGISTER_USER_CANCEL = "REGISTER_USER_CANCEL";
// CREATE LISTINGS
export const CREATE_LISTING = "CREATE_LISTING";
export const CREATE_LISTING_SUCCESS = "CREATE_LISTING_SUCCESS";
export const CREATE_LISTING_FAILED = "CREATE_LISTING_FAILED";
export const CREATE_LISTING_CANCEL = "CREATE_LISTING_CANCEL";

// UPDATE LISTINGS
export const UPDATE_LISTING = "UPDATE_LISTING";
export const UPDATE_LISTING_SUCCESS = "UPDATE_LISTING_SUCCESS";
export const UPDATE_LISTING_CANCEL = "UPDATE_LISTING_CANCEL";

// LOAD ALL LISTINGS
export const LOAD_ALL_LISTINGS = "LOAD_ALL_LISTINGS";
export const LOAD_ALL_LISTINGS_SUCCESS = "LOAD_ALL_LISTINGS_SUCCESS";

// LOAD USER LISTINGS
export const LOAD_MY_LISTINGS = "LOAD_MY_LISTINGS";
export const LOAD_MY_LISTINGS_SUCCESS = "LOAD_MY_LISTINGS_SUCCESS";

// DELETE LISTINGS
export const DELETE_LISTING = "DELETE_LISTING";
export const DELETE_LISTING_SUCCESS = "DELETE_LISTING_SUCCESS";

// LOAD DONOR LISTINGS
export const LOAD_DONOR_LISTINGS = "LOAD_DONOR_LISTINGS";
export const LOAD_DONOR_LISTINGS_SUCCESS = "LOAD_DONOR_LISTINGS_SUCCESS";
export const DELETE_DONOR_LISTING = "DELETE_DONOR_LISTING";
export const DELETE_DONOR_LISTING_SUCCESS = "DELETE_DONOR_LISTING_SUCCESS";
// Wanna Help
export const WANNA_HELP = "WANNA_HELP";

// Filter listings
export const FILTER_LISTINGS = "FILTER_LISTINGS";
export const FILTER_LISTINGS_SUCCESS = "FILTER_LISTINGS_SUCCESS";
// Search Listings by Search Filter
export const SEARCH_LISTINGS = "SEARCH_LISTINGS";
export const SEARCH_LISTINGS_SUCCESS = "SEARCH_LISTINGS_SUCCESS";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";